name: CI (Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          build-args: PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          tags: test-img:local
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run tests & collect artifacts
        run: |
          mkdir -p artifacts
          docker run --rm -v "$PWD/artifacts:/out" test-img:local
      - uses: actions/upload-artifact@v4
        with:
          name: dist-and-outputs
          path: artifacts/**
          if-no-files-found: ignore